[tools]
actionlint = "1.7.12"
rust = "1.97.1"
cargo-binstall = "1.21.0"
"aqua:nextest-rs/nextest/cargo-nextest" = "0.9.140"
just = "1.58.0"

[settings]
cargo.binstall_only = true
cargo.binstall_quickinstall = true
lockfile = true

[tasks.actionlint]
run = "actionlint"
